insert into messages (thread_id, date_time_stamp, read_receipt, sent_from_user_id, sent_to_user_id, content) values (99, '7/8/2022, 12:16:00 AM', false, 1, 391, 'orci mauris lacinia sapien quis libero nullam sit amet turpis elementum');
insert into messages (thread_id, date_time_stamp, read_receipt, sent_from_user_id, sent_to_user_id, content) values (99, '7/8/2022, 8:12:00 PM', false, 391, 1, 'nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est');
insert into messages (thread_id, date_time_stamp, read_receipt, sent_from_user_id, sent_to_user_id, content) values (99, '7/9/2022, 5:49:00 AM', false, 1, 391, 'diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis');
insert into messages (thread_id, date_time_stamp, read_receipt, sent_from_user_id, sent_to_user_id, content) values (99, '7/9/2022, 1:20:00 PM', false, 391, 1, 'sed vestibulum sit amet cursus id turpis integer aliquet massa id');


insert into messages (thread_id, date_time_stamp, read_receipt, sent_from_user_id, sent_to_user_id, content) values (392, '7/8/2022, 3:36:00 AM', false, 1, 373, 'ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna');
insert into messages (thread_id, date_time_stamp, read_receipt, sent_from_user_id, sent_to_user_id, content) values (392, '7/8/2022, 10:32 pM', false, 373, 1, 'at feugiat non pretium quis lectus suspendisse potenti in eleifend quam');
insert into messages (thread_id, date_time_stamp, read_receipt, sent_from_user_id, sent_to_user_id, content) values (392, '7/9/2022, 4:27:00 AM', false, 1, 373, 'ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem');
insert into messages (thread_id, date_time_stamp, read_receipt, sent_from_user_id, sent_to_user_id, content) values (392, '7/9/2022, 6:11:00 PM', false, 373, 1, 'rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet');
insert into messages (thread_id, date_time_stamp, read_receipt, sent_from_user_id, sent_to_user_id, content) values (392, '7/10/2022, 3:36:00 AM', false, 1, 373, 'ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna');
insert into messages (thread_id, date_time_stamp, read_receipt, sent_from_user_id, sent_to_user_id, content) values (392, '7/10/2022, 10:32 pM', false, 373, 1, 'at feugiat non pretium quis lectus suspendisse potenti in eleifend quam');

insert into messages (thread_id, date_time_stamp, read_receipt, sent_from_user_id, sent_to_user_id, content) values (434, '7/11/2022, 3:22:00 AM', false, 1, 394, 'vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus');
insert into messages (thread_id, date_time_stamp, read_receipt, sent_from_user_id, sent_to_user_id, content) values (434, '7/11/2022, 2:59:00 PM', false, 394, 1, 'vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget');
insert into messages (thread_id, date_time_stamp, read_receipt, sent_from_user_id, sent_to_user_id, content) values (434, '7/12/2022, 12:41:00 AM', false, 1, 394, 'erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget');
insert into messages (thread_id, date_time_stamp, read_receipt, sent_from_user_id, sent_to_user_id, content) values (434, '7/12/2022, 4:17:00 PM', false, 394, 1, 'vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet');
insert into messages (thread_id, date_time_stamp, read_receipt, sent_from_user_id, sent_to_user_id, content) values (434, '7/13/2022, 3:22:00 AM', false, 1, 394, 'vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus');
insert into messages (thread_id, date_time_stamp, read_receipt, sent_from_user_id, sent_to_user_id, content) values (434, '7/13/2022, 2:59:00 PM', false, 394, 1, 'vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget');
insert into messages (thread_id, date_time_stamp, read_receipt, sent_from_user_id, sent_to_user_id, content) values (434, '7/14/2022, 12:41:00 AM', false, 1, 394, 'erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget');
insert into messages (thread_id, date_time_stamp, read_receipt, sent_from_user_id, sent_to_user_id, content) values (434, '7/14/2022, 4:17:00 PM', false, 394, 1, 'vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet');